
name: Theme Review 

on: repository_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Download Theme
      run: |
        curl -L -o theme.zip "${{ github.event.client_payload.theme_zip }}"
        unzip theme.zip
  
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Print Environment
      env:
          GITHUB_EVENT: ${{ toJSON(github.event.client_payload) }}
      run: echo "$GITHUB_EVENT"
      
    - name: Test My Theme
      id: test
      uses: WordPress/theme-review-action@trunk
      with:
        root-folder: ${{ github.event.client_payload.theme_slug }}
        accessible-ready: ${{ github.event.client_payload.accessible_ready }}
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: UI Check Output
        path: ${{ steps.test.outputs.ui-check-output }}
        retention-days: 5
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Logs
        path: ${{ steps.test.outputs.logs }}   
    - name: Post UI Errors
      if: |
        ${{ always() }}       
      run: |
        curl --request POST \
          --url 'https://wordpress.org/themes/wp-json/themes/v1/github/${{ github.event.client_payload.theme_slug }}/${{ github.event.client_payload.trac_ticket_id }}' \
          --header 'Authorization: Bearer ${{ secrets.ORG_POST_SECRET }}' \
          --data-urlencode "@${{ steps.test.outputs.logs }}/ui-check-errors.txt"
